"""
List of Constants for Spline_Drawer.py program
"""

#Frame rate
FPS = 30

#Colors
BLACK = (0,0,0)
WHITE = (255, 255, 255)
RED = (255, 0 , 0)
GREEN = (0, 125, 0)
BLUE = (0, 0, 255)

#Window INITing values
INIT_BACKGROUND_COLOR = BLACK
INIT_WINDOW_HEIGHT = 1000
INIT_WINDOW_WIDTH = 1200

#Spline INITing values
INIT_POINT_SIZE = 5
INIT_POINT_COLOR = BLUE
INIT_START_CONTROL_POINT_COLOR = RED
INIT_END_CONTROL_POINT_COLOR = BLUE
INIT_CONTROL_LINE_COLOR = WHITE
INIT_LINE_COLOR = WHITE
INIT_LINE_THICKNESS = 2
INIT_SEGMENT_STEPS = 100
